apiVersion: v1
kind: Pod
metadata:
  name: simple-api
spec:
  automountServiceAccountToken: true
  containers:
  - image: registry.class.syscallx86.com/simple-api:v1.0.0
    imagePullPolicy: IfNotPresent
    name: simple-api
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst

